/* SFU Library Suite — shared mock/demo data (fallback when live backend is down).
 * Plain JS (no JSX); loaded before the app's babel script so window.SFUMock is
 * available to all three apps. Single source of truth for fallback data. */
(function () {
const MOCK_RESULTS = [
  {
    id: "W2971912755",
    title: "Deep learning for predicting drug–target interactions and drug bioactivity",
    authors: ["Öztürk, H.", "Özgür, A.", "Ozkirimli, E."],
    year: 2018,
    source: "Molecular Informatics",
    volume: "37", issue: "1-2",
    doi: "10.1002/minf.201700113",
    cited_by: 847,
    type: "article",
    peer_reviewed: true,
    abstract: "Predicting drug–target interaction (DTI) is an important step in drug discovery and repositioning. In this work, we propose DeepDTA, a deep-learning-based model for the prediction of drug–target binding affinity values. We evaluated our model on two well-known benchmark datasets: Davis and KIBA.",
    tldr: "DeepDTA uses CNN-based deep learning to predict drug-target binding affinity, outperforming previous methods on benchmark datasets.",
    access: { type: "open_access", url: "#", label: "Open Access" },
    expanded_terms: ["neural networks", "binding affinity", "chemogenomics", "computational drug discovery"],
    topics: ["Drug Discovery", "Deep Learning", "Bioinformatics"],
    oa_status: true,
  },
  {
    id: "W2794406408",
    title: "Artificial intelligence in drug discovery and development",
    authors: ["Paul, D.", "Sanap, G.", "Shenoy, S.", "Kalyane, D.", "Kalia, K.", "Tekade, R. K."],
    year: 2021,
    source: "Drug Discovery Today",
    volume: "26", issue: "1",
    doi: "10.1016/j.drudis.2020.10.010",
    cited_by: 1243,
    type: "article",
    peer_reviewed: true,
    abstract: "Artificial intelligence (AI) is beginning to transform drug discovery and development. Various AI techniques, including machine learning, deep learning, and natural language processing, are being applied at every stage of the drug discovery pipeline from target identification to clinical trials.",
    tldr: "Comprehensive review of AI/ML applications across the drug discovery pipeline, covering target identification, hit discovery, lead optimization, and clinical trials.",
    access: { type: "sfu_proxy", url: "#", label: "SFU Library via ScienceDirect" },
    expanded_terms: ["machine learning", "pharmaceutical AI", "QSAR", "generative models"],
    topics: ["Pharmaceutical Sciences", "Artificial Intelligence", "Machine Learning"],
    oa_status: false,
  },
  {
    id: "W3120987654",
    title: "Graph neural networks for drug discovery and molecular property prediction",
    authors: ["Gilmer, J.", "Schütt, K. T.", "Maennel, H."],
    year: 2020,
    source: "Nature Machine Intelligence",
    volume: "2", issue: "11",
    doi: "10.1038/s42256-020-00236-4",
    cited_by: 512,
    type: "article",
    peer_reviewed: true,
    abstract: "Graph neural networks (GNNs) have emerged as a powerful paradigm for molecular machine learning, offering a natural representation of molecular graphs. This review covers the development of GNN architectures for property prediction, generative modeling, and drug-target interaction.",
    tldr: "Survey of graph neural network approaches for molecular property prediction and drug discovery, with comparisons across architectures.",
    access: { type: "unpaywall_oa", url: "#", label: "Free via PubMed Central" },
    expanded_terms: ["graph convolution", "molecular fingerprints", "MPNN", "message passing"],
    topics: ["Graph Neural Networks", "Cheminformatics", "Molecular Modeling"],
    oa_status: true,
  },
  {
    id: "W2801234987",
    title: "A survey of transfer learning for drug discovery",
    authors: ["Hu, W.", "Liu, B.", "Gomes, J.", "Zitnik, M.", "Liang, P."],
    year: 2020,
    source: "Journal of Chemical Information and Modeling",
    volume: "60", issue: "8",
    doi: "10.1021/acs.jcim.0c00116",
    cited_by: 334,
    type: "article",
    peer_reviewed: true,
    abstract: "The limited availability of labeled data is one of the most significant challenges in applying deep learning to drug discovery. Transfer learning and pre-training strategies can alleviate this by leveraging large unlabeled molecular datasets.",
    tldr: "Introduces transfer learning strategies for molecular property prediction with limited labeled data, showing improvements across 12 benchmark tasks.",
    access: { type: "sfu_proxy", url: "#", label: "SFU Library via ACS Publications" },
    expanded_terms: ["pre-training", "few-shot learning", "molecular representation", "self-supervised"],
    topics: ["Transfer Learning", "Molecular Property Prediction", "Deep Learning"],
    oa_status: false,
  },
  {
    id: "W3098765432",
    title: "Generative models for molecular design in drug discovery",
    authors: ["Sanchez-Lengeling, B.", "Aspuru-Guzik, A."],
    year: 2018,
    source: "Science",
    volume: "361", issue: "6400",
    doi: "10.1126/science.aat2663",
    cited_by: 1897,
    type: "article",
    peer_reviewed: true,
    abstract: "Generative models—in particular variational autoencoders, generative adversarial networks, and recurrent neural networks—are being applied to molecular design, enabling de novo generation of drug-like molecules with desired properties.",
    tldr: "Perspective on generative AI approaches for de novo molecular design, covering VAEs, GANs, and reinforcement learning methods.",
    access: { type: "sfu_proxy", url: "#", label: "SFU Library via AAAS" },
    expanded_terms: ["VAE", "GAN", "de novo design", "SMILES generation", "reinforcement learning"],
    topics: ["Generative AI", "Molecular Design", "Drug Discovery"],
    oa_status: false,
  },
  {
    id: "W3112345678",
    title: "Molecular transformers for drug property prediction and optimization",
    authors: ["Schwaller, P.", "Laino, T.", "Gaudin, T.", "Bolgar, P."],
    year: 2022,
    source: "ACS Central Science",
    volume: "8", issue: "4",
    doi: "10.1021/acscentsci.2c00117",
    cited_by: 287,
    type: "article",
    peer_reviewed: true,
    abstract: "Transformer-based architectures originally developed for natural language processing have shown remarkable success in chemical applications, learning representations from SMILES strings that capture complex molecular structure-activity relationships.",
    tldr: "Transformer models trained on SMILES strings achieve state-of-the-art performance on molecular property prediction and chemical reaction prediction.",
    access: { type: "open_access", url: "#", label: "Open Access" },
    expanded_terms: ["BERT for molecules", "ChemBERTa", "attention mechanism", "SMILES tokenization"],
    topics: ["Transformers", "NLP for Chemistry", "Property Prediction"],
    oa_status: true,
  },
  {
    id: "W2987654321",
    title: "Predicting clinical drug–drug interactions using a deep learning approach",
    authors: ["Ryu, J. Y.", "Kim, H. U.", "Lee, S. Y."],
    year: 2018,
    source: "Nature Communications",
    volume: "9", issue: "1",
    doi: "10.1038/s41467-018-07953-8",
    cited_by: 623,
    type: "article",
    peer_reviewed: true,
    abstract: "Drug–drug interactions (DDIs) remain a major cause of adverse events in polypharmacy patients. We develop DeepDDI, a deep learning framework that predicts 86 DDI types using structural information about drug pairs.",
    tldr: "DeepDDI predicts 86 types of drug-drug interactions with >92% accuracy using structural drug features and a deep learning classifier.",
    access: { type: "open_access", url: "#", label: "Open Access" },
    expanded_terms: ["polypharmacy", "adverse drug reactions", "DDI prediction", "pharmacovigilance"],
    topics: ["Drug Safety", "Deep Learning", "Computational Pharmacology"],
    oa_status: true,
  },
];

const MOCK_DATABASES = [
  { id: 1, name: "Academic Search Complete", provider: "EBSCOhost", subjects: ["Multidisciplinary"], proxy: true, free: false },
  { id: 2, name: "ScienceDirect", provider: "Elsevier", subjects: ["Science", "Technology", "Medicine"], proxy: true, free: false },
  { id: 3, name: "PubMed Central", provider: "NLM", subjects: ["Biomedical", "Life Sciences"], proxy: false, free: true },
  { id: 4, name: "JSTOR", provider: "JSTOR", subjects: ["Humanities", "Social Sciences"], proxy: true, free: false },
  { id: 5, name: "Web of Science", provider: "Clarivate", subjects: ["Multidisciplinary"], proxy: true, free: false },
  { id: 6, name: "Scopus", provider: "Elsevier", subjects: ["Science", "Technology", "Medicine"], proxy: true, free: false },
  { id: 7, name: "PsycINFO", provider: "EBSCOhost", subjects: ["Psychology", "Behavioral Sciences"], proxy: true, free: false },
  { id: 8, name: "IEEE Xplore", provider: "IEEE", subjects: ["Engineering", "Computer Science"], proxy: true, free: false },
  { id: 9, name: "ACM Digital Library", provider: "ACM", subjects: ["Computer Science"], proxy: true, free: false },
  { id: 10, name: "SpringerLink", provider: "Springer", subjects: ["Science", "Technology"], proxy: true, free: false },
];

// Analytics bundle fallback — mirrors the /analytics panel shapes the server emits.
const ANALYTICS = {
  generated_at: null,
  panels: {
    kpis: { status: "ok", documents: 150413098, snapshot: "June 2026 snapshot",
            queries_30d: 18432, median_latency_ms: 71 },
    ndcg_by_subject: { status: "ok", subjects: [
      { subject: "Natural Sciences", ndcg: 0.58 },
      { subject: "Health & Medicine", ndcg: 0.61 },
      { subject: "Social Sciences", ndcg: 0.54 },
      { subject: "Engineering & CS", ndcg: 0.59 },
      { subject: "Arts & Humanities", ndcg: 0.49 },
    ] },
    reranker_signal: { status: "ok", source: "heuristic_weights", axes: [
      { signal: "title_match", weight: 0.31 },
      { signal: "abstract_match", weight: 0.24 },
      { signal: "recency", weight: 0.15 },
      { signal: "citation_count", weight: 0.12 },
    ] },
    position_bias: { status: "awaiting_click_data", curve: [] },
    model_versions: { status: "ok", updated: null, models: {
      reranker: "sfu-cross-encoder-v1-int8", parser: "Qwen3-1.7B", sparse: "SPLADE bert-base" } },
    session_replay: { status: "awaiting_click_data", sessions: [] },
  },
};

// Index status fallback — mirrors get_index_status (metrics + pack + unpack_jobs).
const INDEX_STATUS = {
  metrics: {
    available: true,
    live_sections: ["social_sciences__recent", "natural_sciences__recent"],
    legs: { bm25f: { ms: 34 }, splade: { ms: 41 }, dense: { ms: 12 }, fusion: { ms: 6 } },
    dense_cache: { cached_docs: 38412, cap: 500000, hit_rate: 0.62 },
  },
  pack: { packed_sections: [
    { id: "social_sciences__recent", base: "social_sciences", era: "recent", docsM: 27.4, live_gb: 20.5, packed_gb: 9.8, ratio: "2.1x" },
    { id: "social_sciences__archive", base: "social_sciences", era: "archive", docsM: 12.1, live_gb: 9.0, packed_gb: 4.3, ratio: "2.1x" },
    { id: "natural_sciences__recent", base: "natural_sciences", era: "recent", docsM: 31.2, live_gb: 23.1, packed_gb: 10.9, ratio: "2.1x" },
    { id: "health_medicine__recent", base: "health_medicine", era: "recent", docsM: 41.2, live_gb: 30.4, packed_gb: 14.2, ratio: "2.1x" },
    { id: "engineering_cs__recent", base: "engineering_cs", era: "recent", docsM: 22.7, live_gb: 16.8, packed_gb: 7.9, ratio: "2.1x" },
    { id: "arts_humanities__recent", base: "arts_humanities", era: "recent", docsM: 15.6, live_gb: 11.5, packed_gb: 5.4, ratio: "2.1x" },
  ] },
  unpack_jobs: {},
};

// Personas fallback — mirrors list_personas.
const PERSONAS = {
  personas: {
    all_hot: { hot: ["social_sciences__recent","natural_sciences__recent","health_medicine__recent","engineering_cs__recent","arts_humanities__recent"], kind: "Testbed · all sections hot", testbed: true },
    political_science: { hot: ["social_sciences__recent"], kind: "Subject · recent era", testbed: false },
    biomedical: { hot: ["health_medicine__recent"], kind: "Subject · recent era", testbed: false },
    cs_ml: { hot: ["engineering_cs__recent"], kind: "Subject · recent era", testbed: false },
  },
  sections: ["natural_sciences","health_medicine","social_sciences","engineering_cs","arts_humanities"],
  era_boundary_year: 2010,
  live_sections: ["social_sciences__recent","natural_sciences__recent"],
  cold_sections: ["health_medicine__recent","engineering_cs__recent","arts_humanities__recent"],
  active_profile: "political_science",
};

window.SFUMock = {
  results: MOCK_RESULTS,
  databases: MOCK_DATABASES,
  analytics: ANALYTICS,
  indexStatus: INDEX_STATUS,
  personas: PERSONAS,
};
})();
